version: '3.9'

services:
  web:
    container_name: frontend-app
    build:
      target: dev
      context: ./frontend
    volumes:
      - "./frontend:/usr/apps/frontend"
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    expose:
      - 3000