name: Deploy to Elastic Beanstalk

on:
  push

jobs:
  deploy:
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Get SHORT_SHA
        run: echo "SHORT_SHA=${GITHUB_SHA::8}" >> $GITHUB_ENV
      - name: Create ZIP
        run: zip -r deploy_package.zip ./
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: eu-west-2
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      # - name: Upload to S3
      #   run: aws s3 cp deploy_package.zip s3://elasticbeanstalk-eu-west-2-905084406720/docker-react/
      # - name: Create application version on Beanstalk
      #   run: |
      #       aws elasticbeanstalk create-application-version \
      #       --application-name docker-react \
      #       --source-bundle S3Bucket="s3://elasticbeanstalk-eu-west-2-905084406720/",S3Key="docker-react/deploy_package.zip" \
      #       --version-label "ver-${{ env.SHORT_SHA }}" \
      #       --description "commit-sha-$GITHUB_SHA" \
      #       --region eu-west-2
      # - name: Deploy app to Beanstalk
      #   run: |
      #       aws elasticbeanstalk update-environment --environment-name Dockerreact-env --version-label ver-${{ env.SHORT_SHA }}
      - name: Deploy to Beanstalk
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: docker-react
          environment_name: Dockerreact-env
          version_label: ver-${{ env.SHORT_SHA }}
          region: eu-west-2
          deployment_package: deploy_package.zip
          use_existing_version_if_available: true