name: CI Test and Image Build
on:
  push:
    branches:
      - 'ch-**'
      - 'ft-**'
      - 'bg-**'
      - 'module-**'
    paths:
      - '**.js'
      - '**.yml'
      - '**.json'

jobs:
  test-frontend:
    runs-on: ubuntu-18.04
    container: node:16-alpine3.14
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install dependencies
        working-directory: ./frontend
        run: npm ci
      - name: Run tests
        working-directory: ./frontend
        run: npm test

  # build-and-push-frontend-image:
  #   runs-on: ubuntu-18.04
  #   needs: test-frontend
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3
  #     - name: Populate SHORT_SHA
  #       run: echo "SHORT_SHA=${GITHUB_SHA::8}" >> $GITHUB_ENV
  #     - name: Docker login
  #       uses: docker/login-action@v1
  #       with:
  #         username: ${{ secrets.DOCKER_HUB_USERNAME }}
  #         password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
  #     - name: Set up buildx
  #       uses: docker/setup-buildx-action@v1
  #     - name: Build image
  #       uses: docker/build-push-action@v2
  #       with:
  #         context: ./frontend
  #         file: ./frontend/Dockerfile
  #         builder: ${{ steps.buildx.outputs.name }}
  #         push: true
  #         target: prod
  #         tags: "${{ secrets.DOCKER_HUB_USERNAME }}/docker-react:${{ env.SHORT_SHA }}"
