name: CI Test and Image Build
on:
  push:
    branches:
      - 'ch-**'
      - 'ft-**'
      - 'bg-**'
      - 'module-**'
    paths:
      - '**.js'
      - '**.yml'
      - '**.json'

jobs:
  test-frontend:
    runs-on: ubuntu-18.04
    container: node:16-alpine3.14
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install dependencies
        working-directory: ./frontend
        run: npm ci
      - name: Run tests
        working-directory: ./frontend
        run: npm test -- --coverage
